require "user.autocmds"
require "user.launch"
require "user.keymaps"
require "user.options"

-- Plugins
spec "user.alpha"
spec "user.bqf"
spec "user.cmp"
spec "user.gitsigns"
-- spec "user.harpoon"
spec "user.indent-blankline"
spec "user.lspconfig"
spec "user.markdown-preview"
spec "user.mason"
spec "user.navic"
spec "user.none-ls"
spec "user.nvim-tree"
spec "user.project"
spec "user.simple-plugins"
spec "user.telescope"
spec "user.treesitter"
spec "user.ufo"
spec "user.whichkey"

-- Extras
spec "user.extras.codeium"
spec "user.extras.colorizer"
spec "user.extras.dressing"
-- spec "user.extras.eyeliner"
spec "user.extras.fidget"
spec "user.extras.flash"
spec "user.extras.gitlinker"
spec "user.extras.hardtime"
spec "user.extras.helpview"
spec "user.extras.illuminate"
spec "user.extras.neogit"
spec "user.extras.neoscroll"
spec "user.extras.neotab"
spec "user.extras.noice"
spec "user.extras.oil"
spec "user.extras.tabby"

-- DAP
-- spec "user.dap.nvim-dap"

-- Initialize lazy after the plugin table is defined
require "user.lazy"
